package by.htp.courses.controller;

public enum CommandName {
	MAIN_PAGE, TEACHERS_PAGE, SUBJECTS_PAGE, SIGN_UP_PAGE, SIGN_IN, SIGN_UP, SIGN_OUT, 
	USERS_EDIT, USERS_SEARCH, SUBJECTS_EDIT, SUBJECTS_SEARCH, LOCALIZATION, CHILDREN_EDIT, 
	LESSONS_EDIT, PROFILE_EDIT, PROFILE_EDIT_PAGE, ERROR_PAGE;

}
